### ISSUE TITLE
Server_GameCustomMessage error

### ISSUE THREAD

**Issue by avioane** [dabo123148/WarlightMod#9]
when trying to send money (Trading - Gift Money - Select Player - Send money)
ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V2" Failed: [string "Server_GameCustomMessage.lua"]:87: java.lang.NullPointerException
__newindex (External Function)
(Unknown Function) (Server_GameCustomMessage.lua:87)

GameID=14431862
Hook=Server_GameCustomMessage

**Comment by dabo123148** [comment]
should be fixed now, can you verify that it is fixed

**Comment by avioane** [comment]
I tried it in our first nations game and still got the same error

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 8, 2017 at 11:48 AM, dabo123148<notifications@github.com> wrote:    
should be fixed now, can you verify that it is fixed

**Comment by dabo123148** [comment]
the reason for that may be that I accidentialy reloaded the wrong mod so there was still the old code for the mod can you try again please.

**Comment by avioane** [comment]
the request was sent (so this is new), but still crashed, with a different error:

Sorry, the mod "Advanced Diplo Mod V2" has failed.  Error: 
History.lua:(140,1-59): attempt to index a nil value

**Comment by dabo123148** [comment]
yes, i am already working on that one

**Comment by dabo123148** [comment]
fixed
